version: ~> 1.0
sudo: false
language: node_js
node_js:
  - '4'
  - '6'
  - '8'
  - '10'
  - '12'
  - '14'
  - '15'
matrix:
  fast_finish: true
  allow_failures: []
cache: npm
install:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/master/scripts/node-install.bash)"
before_script:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/master/scripts/node-verify.bash)"
after_success:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/master/scripts/surge.bash)"
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/master/scripts/node-publish.bash)"
notifications:
  email:
    recipients: >-
      SQk3sWABRJV7SKHDSGzyuOs3/ACwO9T/DOVLzdNGx1iKzDhR3tim9SVANtWU/XaSuSyWmLnsy/XE5k02hxAWKhgxIQe9MqrCjDtQrBkCdmwd9edBu5w44SQEat5DC2ajVSiDK6+vQFkh2whUXsQWj3oClIch1Edi7yfopWh/3GXsJl6FEozYeEIlxXw6h/n3nWTp1adWr9DCgaPKa9b7x3BzfwaR0eRMY2Nos2oYaAI9LLO026nTlHVgF1Rj6PkD2U9ynaitm52skO63SNal0B0ReJFYDuOqgF0u1b/HeQGv2akT4RMi/0581QJHYJyGlbELyppzjHHdbbsfnRQwPjWa+UzcCn4IijYA73vtcye9WfvdwbyFL5aEQTudnzDWh7WOmqkBLipRbObsbVLtXvmEoH6sT275aHoIu6fr6xze09mAhEyyYdVcqqUzem0mvRFRyirVeUNPTtiqZG8VjzZCE2AIg/uHzydzX2k1Ed7MI2bv7FGPRj7pvMm8H1TqwZvUAPjZKjWVwQR7YFnGzkc6KdtNb68tBEL7wxQvLS652Rbvd/Del3fXk/3ZgpNtMzb1n2KCiDv8YKlxSbCnXBbsIlLtIfunvZF5lt81OvSX2IZ79nJaJHjkn//HYQYO+Itjt7G2oJJm6kzaTH0EeRz9MW9+f6nNjRXfyjPL6SY=
