version: ~> 1.0
sudo: false
language: node_js
node_js:
  - '10'
  - '12'
  - '13'
  - '14'
matrix:
  fast_finish: true
  allow_failures: []
cache: npm
install:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/master/scripts/node-install.bash)"
before_script:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/master/scripts/node-verify.bash)"
after_success:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/master/scripts/surge.bash)"
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/master/scripts/node-publish.bash)"
notifications:
  email:
    recipients: >-
      GiQjo2RLWvkJnnbkblie7c4eDsRv+4wRLsNPHjP039lAL+gvQo3CUei4YHlMrHeo06AvKile/aX7xuTIA46WuumfJ3HECQnbiwMem1yTWCaIjkS0wqFVVny4XFcDoWl3G4uyV2In4+7e4cx7/xQCIQhV4dzFv/UHnQ3KCiZqL1fauJ99x8v7lCClKEVHFTbf2zEfMLudIW/hQjlr2kQtj1eQKDNXvT2WzR1O81NSUIOAdoaDYWnMQraZVKA8OB9oehaI72WT63H+KPbZg4YFYPUNkciuq0O7SIiU718Hr32Bx9ymx3BZ6LUtFqw/jbvSdTwQLKgsHbizfT3sEXy2HevsfdDGEc3mZgukFuPA8tnp/oxsWw1S15SNU5rVnHYYt6ciWOr+2K3Zhy0X9rKae7RU10pMU2hVTCbqkP+m1GbUPsbQHif1/r0S5UjK42w7H2RFuA/EOkNg5/r+xQte08N/HO13GF8jjZTxs05qwDTTY39gpyPoa5qCf6CYwcPe7Af6CBgSSVokOzlrgMLXsRukdrhTtFQzg/EOgPY0ToL1B9OoLa+4XmOprdOM0rX6Re7wiDnQfNSFYWFc4YPd2RhiDW7bDrcz4PqeIOEQclEx5vN5rJiOoPnQLBYpU9oHw9+Q5pHpYGnysA05O/V3sPNX4ZWu5TE9lfodkz2DAug=
