version: ~> 1.0
sudo: false
language: node_js
node_js:
  - '10'
  - '12'
  - '13'
  - '14'
matrix:
  fast_finish: true
  allow_failures: []
cache: npm
install:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/master/scripts/node-install.bash)"
before_script:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/master/scripts/node-verify.bash)"
after_success:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/master/scripts/surge.bash)"
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/master/scripts/node-publish.bash)"
notifications:
  email:
    recipients: >-
      WsVXzO8GwzPxrTLjxjGOwQn+0xG/4PQ4NdI7muGIlD+PkdHQs6E0SHsVEZlbKf4bByphniwnHN1LL1hSIA213Kl6cglicUobnjgcRXBo+hR9e+7retq7/KSMuE90SxnrOEcWvKnKez+mW2oJHy+1jsV25fR+BEhp9x7Wsh0VIQPicbrdppDofx241SDMmC8NTu3LHfHmOY3ZloLtJ7M+YAiA9kPl67MFemrnVOGPlFgAgk7YXUJKWV3iGlZpsrMzFEXb+tfTpb6Fsrbx37g7MCLsMjYG37Hn4qzuJROU9sHATbzfrcwV8c2Tz5P9glhtOqbVXALCsmbR+jEdzXUj8iW5VW5gqeBBl0zmNPO3hJm5KFXlkXiwC01y0xT7jbiQyte5MKGBPxFonlmfraqqk48Ne56hRXaOEDLtb8kmT/W/sy+crkE9oRdYxq3mvyMJ/NqZByLhIAQcFwBdfJ80zr8zECcxnTID9Lb2nc4diD3FPXsZEajwgRZqGDmi25iXPTnJDlKoBrga/0AoYU+AQY71GGmBFVPE8hFs4Uhes/CUZoTerjIO2lHIHwVbraPB0A1A6lIZHH/Dru+qiDfStf08drt815Us5ssukeSLU3TQOcyR7lHBtzUv7LwIHI1mlSS8+bCKdh/1LRNALOZiMkGm2LOYwmubGb7l4kzFNSk=
